Implemented restricted snippet search within package
abelsiqueira/Jet.jl pull request #16
Opened 2020-10-14 04:00 UTC by vcoutasso

Resolves #3

2020-10-14 12:31 UTC, abelsiqueira requested changes
This is great, thanks. I made a small modification, and I would also ask that you write a simple test in "Basic functionality". In may need to add a new string to "output.jl".

2020-10-14 12:31 UTC, abelsiqueira commented on src/actions.jl
> +      jet_snippet_in(keyword, pkg, should_print)
```suggestion
    kws = [str[first+1:sep-1], str[last+1:end]]

    if kind[1] in ["pkg", "package"] &&
       kind[2] in ["cmd", "command", "snippet"]
      jet_snippet_in(keyword, kws[1], kws[2])
    elseif kind[2] in ["pkg", "package"] &&
           kind[1] in ["cmd", "command", "snippet"]
      jet_snippet_in(keyword, kws[2], kws[1])
```
This was we can accept `pkg:... cmd:...` and `cmd:... pkg:...` as well.

2020-10-14 17:02 UTC, vcoutasso commented
Now that the order of `cmd` and `pkg` do not matter, I was wondering what should be the error message in case anything goes wrong. Before that, I tried to enforce the correct order of actions, but I don't think it makes any more sense after these modifications. 

What are your thoughts?

2020-10-15 12:28 UTC, abelsiqueira commented
Your observation is correct, the error on line 108 throws when the kinds are not right. So it works for `cmd:... cmd:...` as well as `potato:... tomato:...`. So the current error looks good. We can test these cases, of course.

Regarding your test `pkg:Jet cmd:}`, I fear it's not robust, because `cmd:}` already returns only one entry, so maybe something more generic like `pkg:Jet cmd:the`. Thanks again.

2020-10-15 17:58 UTC, merged

2020-10-15 17:58 UTC, abelsiqueira commented
Thanks a lot!

2022-02-15 20:49 UTC, abelsiqueira commented
@all-contributors please add @vcoutasso for code