Added basic coloring using Crayons.jl
abelsiqueira/Jet.jl pull request #17
Opened 2020-10-14 17:25 UTC by ParthPant

This is just an attempt to adding colors to the output using crayons.jl . This can be optimized a lot.
Syntax highlighting for code snippets is not added yet.
This just adds color and underline to the text and nothing more. No line breaks are changes and the bare-bones text remains basically the same.
 
![2020-10-14-225200_1920x1080_scrot_000](https://user-images.githubusercontent.com/30381591/96023567-4283ec00-0e70-11eb-9254-8b6ad0ce02da.png)

2020-10-15 13:22 UTC, abelsiqueira requested changes
Thanks a lot, this is already a great improvement. I've made a few requests on the code to improve it.

2020-10-15 13:22 UTC, abelsiqueira commented on src/format.jl
> +      end
I think we should add these `Crayon`s to the beginning of the files. You can add
```julia
const title_crayon = ...
```
in the first lines and use it here. This will simplify the code a lot.
I can also think of a few improvements that I could have made before, such as writing the output a little better.
```julia
println(title_crayon,  entry["packages"] * "\n")
println(header_crayon, entry["description"] * "\n")
```

2020-10-15 13:22 UTC, abelsiqueira commented on test/runtests.jl
> +using Crayons
I don't think you need this here.

2020-10-15 13:45 UTC, ParthPant commented on src/format.jl
> +      end
yep this is what i initially planned but kind of forgot about it! I'll add that

2020-10-17 14:19 UTC, abelsiqueira approved these changes

2020-10-17 14:19 UTC, abelsiqueira commented on src/format.jl
> +const cmd_crayon = Crayon(foreground = :blue)
```suggestion
const title_crayon    = Crayon(foreground = :light_cyan, bold = true, underline = true)
const desc_crayon     = Crayon(foreground = :light_cyan, bold = true, underline = false)
const cmd_desc_crayon = Crayon(foreground = :green, bold = false)
const cmd_crayon      = Crayon(foreground = :blue)
```

2020-10-17 14:20 UTC, merged

2020-10-17 14:20 UTC, abelsiqueira commented
Thanks!