added Flux.jl
abelsiqueira/Jet.jl pull request #23
Opened 2020-10-21 02:18 UTC by ParthPant

2020-10-22 03:23 UTC, ParthPant commented
I hope this PR fixes the git issues of the last pr

2020-10-22 12:53 UTC, abelsiqueira requested changes
Thanks! I've made a few changes, see if you approve them.

2020-10-22 12:53 UTC, abelsiqueira commented on data.json
> +    "description": "Chains different layers to form a deep neural network model",
```suggestion
    "description": "Chain different layers to form a deep neural network model",
```

2020-10-22 12:53 UTC, abelsiqueira commented on data.json
> +    "description": "Creates a Gradient Descent optimiser with learning rate 0.1",
```suggestion
    "description": "Create a Gradient Descent optimiser with learning rate 0.1",
```

2020-10-22 12:53 UTC, abelsiqueira commented on data.json
> +    "description": "Extracts the parameters of a model `m` which can be later passed on to the `gradient` function",
```suggestion
    "description": "Extract the parameters of a model `m` which can be later passed on to the `gradient` function",
```

2020-10-22 12:53 UTC, abelsiqueira commented on data.json
> +  },
```suggestion
```
This is actually from Zygote.

2020-10-22 12:53 UTC, abelsiqueira commented on data.json
> +    "description": "For each datapoint `d` in `data`, compute the gradient of `loss` with respect to `params` through backpropagation and call the optimizer `opt`. An optional callback is given with
```suggestion
    "description": "Train the model. For each datapoint in `data`, compute the gradient of `loss` with respect to `params` through backpropagation and call the optimizer `opt`. An optional callback is given with the keyword argument `cb`",
```

2020-10-22 15:07 UTC, ParthPant commented on data.json
> +  },
I've changed the package for this to Zygote and added a pkg description for the same

2020-10-25 02:44 UTC, ParthPant commented
@abelsiqueira is this fine or there are some more changes?

2020-10-25 03:18 UTC, abelsiqueira requested changes
Hi, sorry for the delay. I made a simple small change. You can accept it directly on GitHub clicking on the commit suggestion button, if you agree with the change.

2020-10-25 03:18 UTC, abelsiqueira commented on data.json
> +    "description": "The gradient function takes another Julia function f and a set of arguments, and returns the gradient with respect to each argument.",
```suggestion
    "command": "gradient(f, args...)",
    "description": "Computes the gradient of f at each argument, returning a tuple.",
```
I think this is simpler and more informative of the return type.

2020-10-25 04:01 UTC, ParthPant commented on data.json
> +    "description": "The gradient function takes another Julia function f and a set of arguments, and returns the gradient with respect to each argument.",
This seem like a better description!

2020-10-25 04:11 UTC, merged

2020-10-25 04:11 UTC, abelsiqueira commented
Thanks!

2022-02-15 20:47 UTC, abelsiqueira commented
@all-contributors please add @ParthPant for data