Add snippets for DataFrames
abelsiqueira/Jet.jl pull request #8
Opened 2020-10-05 21:56 UTC by Jualns

add somethings functions of DataFrames

2020-10-05 22:46 UTC, abelsiqueira requested changes
Thanks a lot. I requested a few changes that apply to the whole PR, so I will finish checking everything afterwards. Another recommendation is to use imperative phrases, such as "Get the column names".

2020-10-05 22:46 UTC, abelsiqueira commented on data.json
> +    "description": "Column names as Symbols use the propertynames function",
```suggestion
    "description": "Get the column names as Symbols",
```

2020-10-05 22:46 UTC, abelsiqueira commented on data.json
> +      "Columns symbol names",
```suggestion
      "column-names",
```

2020-10-05 22:46 UTC, abelsiqueira commented on data.json
> +      "symbol names"
```suggestion
      "columns"
```

2020-10-05 22:46 UTC, abelsiqueira commented on data.json
> +    "description": "Column names can be obtained as string using the names function",
There's no need to mention the function again. Only what the snippet does.

2020-10-05 22:46 UTC, abelsiqueira commented on data.json
> +      "names"
So far I'm not sure how I'm gonna use the tags, but it's probably better if we use them lowercase and separated by `-`.

2020-10-12 20:08 UTC, Jualns reviewed
I adjusted your recommendations.

2020-10-12 20:08 UTC, Jualns commented on data.json
> +      "Columns names",
```suggestion
      "columns-names",
```

2020-10-12 20:08 UTC, Jualns commented on data.json
> +      "String names columns",
```suggestion
      "name-columns",
```

2020-10-12 20:29 UTC, abelsiqueira commented on data.json
> +    "description": "The last functions can be used to look at the last X rows of a data frame",
```suggestion
    "description": "Look at the last X rows of a data frame",
```

2020-10-12 20:30 UTC, abelsiqueira commented on data.json
> +      "rows"
```suggestion
      "last-rows",
      "print-rows",
      "rows"
```

2020-10-12 20:36 UTC, Jualns commented on data.json
> +    "description": "Column names can be obtained as string using the names function",
```suggestion
    "description": "Obtain columns name",
```

2020-10-12 20:38 UTC, Jualns commented on data.json
> +      "print rows",
```suggestion
    "description": "Look at the firs X rows of a data frame",
    "kind": "snippet",
    "package": "DataFrames",
    "tags": [
      "first",
      "first-rows",
      "print-rows",
```

2020-10-12 20:40 UTC, Jualns commented on data.json
> +      "add columns",
```suggestion
    "description": "Add columns to it one by one",
    "kind": "snippet",
    "package": "DataFrames",
    "tags": [
      "add-columns",
```

2020-10-12 20:43 UTC, Jualns commented on data.json
> +      "add rows",
```suggestion
    "description": "Add Rows as tuples or vectors, where the order of elements matches that of columns",
    "kind": "snippet",
    "package": "DataFrames",
    "tags": [
      "add-rows",
```

2020-10-12 20:45 UTC, Jualns commented on data.json
> +      "show dataframe"
```suggestion
    "description": "Printing all rows or columns, just use allrows=true or allcols=true.",
    "kind": "snippet",
    "package": "DataFrames",
    "tags": [
      "print-dataframe",
      "show",
      "show-all-columns",
      "show-all-rows",
      "show-dataframe"
```

2020-10-12 20:52 UTC, abelsiqueira commented on data.json
> +      "names"
```suggestion
      "column-names",
      "names"
```

2020-10-12 20:54 UTC, abelsiqueira commented on data.json
> +    "description": "Add columns to it one by one in DataFrame",
```suggestion
    "description": "Add a column named `A` to the the DataFrame `df`",
```

2020-10-12 20:57 UTC, abelsiqueira commented on data.json
> +    "description": "Add Rows as tuples or vectors, where the order of elements matches that of columns",
```suggestion
    "description": "Add a new row as a tuple or vector, where the order of elements matches that of the columns of `df`",
```

2020-10-12 21:00 UTC, abelsiqueira commented on data.json
> +  },
```suggestion
  {
    "command": "show(df, allrows=true, allcols=true)",
    "description": "Print all rows and/or columns of the DataFrame `df`",
    "kind": "snippet",
    "package": "DataFrames",
    "tags": [
      "print-dataframe",
      "show",
      "show-all-columns",
      "show-all-rows",
      "show-dataframe"
    ]
  },
```

2020-10-12 21:20 UTC, merged

2022-02-15 20:50 UTC, abelsiqueira commented
@all-contributors please add @Jualns for data